### ISSUE TITLE
gitignore deve ignorar pasta bin e obj

### ISSUE THREAD

**Issue by luisrudge** [diasfulvio/NetCanducciCep#1]
O melhor seria usar um gitignore próprio pro visual studio:
https://www.gitignore.io/api/visualstudio

**Comment by diasfulvio** [comment]
Foi alterado.!

**Comment by luisrudge** [comment]
Boa! Mas ainda falta deletar as pastas antigas (bin e obj)

**Comment by luisrudge** [comment]
Você quer que eu faça um pull request com essas pastas deletadas?
