### ISSUE TITLE
Transformar projeto em BCL

### ISSUE THREAD

**Issue by luisrudge** [diasfulvio/NetCanducciCep#2]
Ao invés de manter vários projetos, é melhor criar uma lib PCL que pode ser adicionada em qualquer projeto

**Comment by diasfulvio** [comment]
Vou estudar sobre o assunto! Obrigado...

**Comment by luisrudge** [comment]
É legal deixar a issue aberta pra continuar a discussão quando você tiver mais conhecimento sobre o assunto
