### ISSUE TITLE
a classe ZipCode não condiz com o nome

### ISSUE THREAD

**Issue by luisrudge** [diasfulvio/NetCanducciCep#3]
A classe `ZipCode` (https://github.com/diasfulvio/NetCanducciCep/blob/master/Canducci/Canducci/ZipCode.cs) não contém um Cep, e sim as informações do Cep.
Talvez um melhor nome seja `ZipCodeInfo`

**Comment by diasfulvio** [comment]
Foi alterado para ZipCodeInfo

**Comment by luisrudge** [comment]
Boa!
