### ISSUE TITLE
ZipLoad.TryParse sendo usado de maneira errada

### ISSUE THREAD

**Issue by luisrudge** [diasfulvio/NetCanducciCep#4]
Normalmente, o `TryParse` transforma uma string em algum outro objeto. Ou seja, `TryParse` não pode devolver outra string, teria que devolver um objeto novo que pode chamar `ZipCode` (o atual `ZipCode` também deve ser renomeado #3).

https://github.com/diasfulvio/NetCanducciCep/blob/master/Canducci/Canducci.Test/Program.cs#L17

Mais informações sobre o `TryParse`: http://www.fatagnus.com/why-you-should-use-tryparse-in-c/

**Comment by diasfulvio** [comment]
Foi retirado esse método ... obrigado

**Comment by luisrudge** [comment]
Boa!
