### ISSUE TITLE
Trocar xml por json

### ISSUE THREAD

**Issue by luisrudge** [diasfulvio/NetCanducciCep#5]
Seria bom utilizar JSON ao invés de XML, já que o tráfego de dados é bem menor.

**Comment by diasfulvio** [comment]
Isso eu não vou mudar. porque, não quero minha biblioteca dependendo de nenhuma. e outra esse Web Service é rápido.

**Comment by diasfulvio** [comment]
Por enquanto vai ficar assim pela compatibilidade. Não quero nenhuma biblioteca adiciona!

**Comment by diasfulvio** [comment]
Obrigado se tiver algo a mais !!! o código foi remodelado!

**Comment by luisrudge** [comment]
Como assim compatibilidade? Você não quer adicionar uma dependência?
