### ISSUE TITLE
ZipLoad

### ISSUE THREAD

**Issue by luisrudge** [diasfulvio/NetCanducciCep#8]
Não tem porque ter os dois métodos `Find()` e `Find(string zip)`. Somente o segundo é necessário.

**Comment by diasfulvio** [comment]
Se ele passar no construtor usa Find();
Se ele não passar no construtor usa Find(string zip);

Essa é a diferença!, então há as duas possibilidades

**Comment by diasfulvio** [comment]
Tem dois métodos Find com parâmetros agora e o métodos são statics
